on: pull_request
name: Pull request test and build
jobs:
  flutter-package:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: flutter
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
      - name: Build web
        run: |
          flutter pub get
          dart format --set-exit-if-changed .
          flutter analyze
          flutter test --dart-define=golden_tolerance=5
  flutter-example:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: flutter/example
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
      - name: Build web
        run: |
          flutter pub get
          dart format --set-exit-if-changed .
          flutter analyze
          flutter test
          flutter build web